#!/usr/bin/env bash
# generado inicialmente con comando
# export APPNAME=test-ndk && py2txt ~/dropbox/learning/docker.py | bash 
# substitute this with your main script
echo "Hello world. Docker app test-ndk created and running"
